# Generated by Django 6.0.6 on 2026-06-15 20:20

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Condominium',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('document_number', models.CharField(blank=True, max_length=32)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('postal_code', models.CharField(blank=True, max_length=16)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blocks', to='core.condominium')),
            ],
            options={
                'ordering': ['condominium__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CondominiumMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('SUPERADMIN', 'Superadmin'), ('CONDO_ADMIN', 'Admin do condominio'), ('SYNDIC', 'Sindico'), ('COUNCIL', 'Conselho'), ('STAFF', 'Funcionario'), ('RESIDENT', 'Morador'), ('OWNER', 'Proprietario'), ('TENANT', 'Inquilino')], max_length=32)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='core.condominium')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_condominium_invites', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='condominium_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['condominium__name', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='CondominiumSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allow_council_view_all_tickets', models.BooleanField(default=False)),
                ('condominium', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='settings', to='core.condominium')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Condominium settings',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('number', models.CharField(max_length=40)),
                ('floor', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='units', to='core.block')),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='core.condominium')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['condominium__name', 'block__name', 'number'],
            },
        ),
        migrations.CreateModel(
            name='UnitOccupancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('occupancy_type', models.CharField(choices=[('OWNER', 'Proprietario'), ('TENANT', 'Inquilino'), ('RESIDENT', 'Morador'), ('DEPENDENT', 'Dependente')], max_length=32)),
                ('is_primary', models.BooleanField(default=False)),
                ('starts_at', models.DateField(blank=True, null=True)),
                ('ends_at', models.DateField(blank=True, null=True)),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unit_occupancies', to='core.condominium')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occupancies', to='core.unit')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unit_occupancies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['condominium__name', 'unit__number', 'user__username'],
            },
        ),
        migrations.AddIndex(
            model_name='condominium',
            index=models.Index(fields=['slug'], name='core_condom_slug_cdc47d_idx'),
        ),
        migrations.AddIndex(
            model_name='condominium',
            index=models.Index(fields=['is_active'], name='core_condom_is_acti_d853b7_idx'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['condominium', 'is_active'], name='core_block_condomi_655d9b_idx'),
        ),
        migrations.AddConstraint(
            model_name='block',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('condominium', 'name'), name='uniq_active_block_name_condo'),
        ),
        migrations.AddIndex(
            model_name='condominiummembership',
            index=models.Index(fields=['condominium', 'role', 'is_active'], name='core_condom_condomi_fe0bbe_idx'),
        ),
        migrations.AddIndex(
            model_name='condominiummembership',
            index=models.Index(fields=['user', 'is_active'], name='core_condom_user_id_2a08af_idx'),
        ),
        migrations.AddConstraint(
            model_name='condominiummembership',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('condominium', 'user'), name='uniq_active_member_condo_user'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['condominium', 'is_active'], name='core_unit_condomi_ed2370_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['condominium', 'block', 'number'], name='core_unit_condomi_62ef63_idx'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(condition=models.Q(('block__isnull', False), ('is_active', True)), fields=('condominium', 'block', 'number'), name='uniq_active_unit_block_no'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(condition=models.Q(('block__isnull', True), ('is_active', True)), fields=('condominium', 'number'), name='uniq_active_unit_no_no_block'),
        ),
        migrations.AddIndex(
            model_name='unitoccupancy',
            index=models.Index(fields=['condominium', 'unit', 'is_active'], name='core_unitoc_condomi_50b1d9_idx'),
        ),
        migrations.AddIndex(
            model_name='unitoccupancy',
            index=models.Index(fields=['user', 'is_active'], name='core_unitoc_user_id_c81aa0_idx'),
        ),
        migrations.AddConstraint(
            model_name='unitoccupancy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('condominium', 'unit', 'user', 'occupancy_type'), name='uniq_active_occupancy_user_type'),
        ),
        migrations.AddConstraint(
            model_name='unitoccupancy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_primary', True)), fields=('condominium', 'unit'), name='uniq_active_primary_unit'),
        ),
    ]
