# Generated by Django 6.0.6 on 2026-06-16 15:29

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_categories', to='core.condominium')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['condominium__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Aberto'), ('IN_PROGRESS', 'Em andamento'), ('RESOLVED', 'Resolvido'), ('CLOSED', 'Fechado')], db_index=True, default='OPEN', max_length=24)),
                ('priority', models.CharField(choices=[('LOW', 'Baixa'), ('NORMAL', 'Normal'), ('HIGH', 'Alta'), ('URGENT', 'Urgente')], db_index=True, default='NORMAL', max_length=24)),
                ('resolved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='core.condominium')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='core.unit')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.ticketcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('is_internal', models.BooleanField(db_index=True, default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_comments', to=settings.AUTH_USER_MODEL)),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_comments', to='core.condominium')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='tickets.ticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ticketcategory',
            index=models.Index(fields=['condominium', 'is_active'], name='tickets_tic_condomi_95d0a3_idx'),
        ),
        migrations.AddConstraint(
            model_name='ticketcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('condominium', 'name'), name='uniq_active_ticket_category_name_condo'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['condominium', 'status', 'is_active'], name='tickets_tic_condomi_9c9456_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['condominium', 'priority', 'is_active'], name='tickets_tic_condomi_4a4d3b_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['condominium', 'created_at'], name='tickets_tic_condomi_ee5d22_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_by', 'is_active'], name='tickets_tic_created_90f46d_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assigned_to', 'status'], name='tickets_tic_assigne_e36302_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketcomment',
            index=models.Index(fields=['condominium', 'ticket', 'created_at'], name='tickets_tic_condomi_f4d824_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketcomment',
            index=models.Index(fields=['author', 'created_at'], name='tickets_tic_author__c5a0ce_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketcomment',
            index=models.Index(fields=['condominium', 'is_internal'], name='tickets_tic_condomi_fc69a4_idx'),
        ),
    ]
