# Generated by Django 6.0.6 on 2026-06-16 14:44

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='announcement_categories', to='core.condominium')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['condominium__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=180)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('PUBLISHED', 'Publicado'), ('ARCHIVED', 'Arquivado')], db_index=True, default='DRAFT', max_length=24)),
                ('is_pinned', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='announcements', to='core.condominium')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_announcements', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='announcements', to='communication.announcementcategory')),
            ],
            options={
                'ordering': ['-is_pinned', '-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementReadReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('read_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='read_receipts', to='communication.announcement')),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='announcement_read_receipts', to='core.condominium')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='announcement_read_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-read_at'],
            },
        ),
        migrations.AddIndex(
            model_name='announcementcategory',
            index=models.Index(fields=['condominium', 'is_active'], name='communicati_condomi_f8c419_idx'),
        ),
        migrations.AddConstraint(
            model_name='announcementcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('condominium', 'name'), name='uniq_active_announcement_category_name_condo'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['condominium', 'status', 'is_active'], name='communicati_condomi_0d7a50_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['condominium', 'published_at'], name='communicati_condomi_de5e0d_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['condominium', 'is_pinned'], name='communicati_condomi_9fe63e_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementreadreceipt',
            index=models.Index(fields=['condominium', 'read_at'], name='communicati_condomi_e2928e_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementreadreceipt',
            index=models.Index(fields=['user', 'read_at'], name='communicati_user_id_cf81fb_idx'),
        ),
        migrations.AddConstraint(
            model_name='announcementreadreceipt',
            constraint=models.UniqueConstraint(fields=('announcement', 'user'), name='uniq_announcement_read_receipt_user'),
        ),
    ]
